services:
  opensearch:
    image: docker-registry.hootops.com/opensearchproject/opensearch:2.15.0
    environment:
      - http.port=9200
      - discovery.type=single-node
      - cluster.name=opensearch
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1